#############################################################################################
############################################################################################
### Running InferCNV for CNV detection of ORv01 Longitudinal scRNAseq Data
### Samples: ORv01 Longitudinal scRNAseq (n=7)
### Author: Grace Walker
### Date: January 22, 2026
#############################################################################################
#############################################################################################

# -------------------------------------------------------------------------------------------
# The following environment set up is required to enable successful import of inferCNV :

   # module load R/4.4.0-openblas-rocky8
   # module load JAGS/4.3.0-gcc7.2.0

# -------------------------------------------------------------------------------------------

# Load libs
library(tidyverse) # dplyr and ggplot
library(Seurat) # for seurat analysis
library(patchwork) # for plotting orientation
library(ggplot2) # for visualization
library(scales) # for plotting
library(presto) # for faster FindMarkers 
library(dittoSeq) # for dittoplot
library(infercnv) # for cnv detection

# Params
options(future.globals.maxSize = 4 * 1024^3)  # Set to 4 GB
gc() # free up memory

options(scipen = 100) # ensure no scientific notation, required for inferCNV
options("preferRaster" = FALSE) # no raster for plotting heatmaps

# Dirs
resDir <- ""
objDir <- ""
gene_pos_path <- ""

# -------------------------------------------------------------------------------------------
# Read in data
s1 <- readRDS(paste0(objDir, 'processed_object_final.rds'))

############################################################################################################
# Run 1 & 2: All timepoints, 1000 per cell type
    # Run 1: T cells as reference 
    # Run 2: T cells + Myeloid cells as reference
############################################################################################################

#### Subset to 1000 cells per cell type
cells_to_keep <- unlist(
  lapply(
    split(Cells(s1), s1$cell_type),
    function(x) sample(x, size = min(1000, length(x)))
  )
)
s1.subset <- subset(s1, cells = cells_to_keep)

# Get gene expr matrix
# Join layers
s1.subset <- JoinLayers(s1.subset, assay = "RNA")

# Extract raw expr data
exp.rawdata <- GetAssayData(s1.subset, assay = "RNA", layer = "counts")


# Check subset distribution
table(s1.subset$cell_type)
table(s1.subset$orig.ident)

#### Create annotation file -- col1=cell_names, col2=cell_type labels
Idents(s1.subset) <- s1.subset$cell_type
annotations <- as.matrix(Idents(s1.subset))
colnames(annotations) <- NULL

#### Create object
# First grab list of all chrs
gene_positions <- read.table(paste0(gene_pos_path,"gene_positions.txt"), sep='\t')
chrs <- unique(gene_positions$V2)

# Subset to only chrs we care about
chrs_to_exclude <- chrs[grepl('chrUn_*',chrs)]


### Run 1: Setting 'normal' cells as T cells

print('Generating infercnv object .....')
infercnv_obj = CreateInfercnvObject(raw_counts_matrix=exp.rawdata, # Raw counts
                                    annotations_file=annotations, # Cell type annotations
                                    delim="\t",
                                    gene_order_file=paste0(gene_pos_path,"gene_positions.txt"), # Gene positions
                                    ref_group_names="T cells",
                                    chr_exclude = chrs_to_exclude) # Customized chr list excluding certain chrs
 

#### Run infercnv 
print('Running infercnv ......')

### On the cutoff parameter:
# The cutoff value determines which genes will be used for the infercnv analysis.
# Genes with a mean number of counts across cells will be excluded.
# For smart-seq (full-length transcript sequencing, typically using cell plate assays rather than droplets), a value of 1 works well.
# For 10x (and potentially other 3'-end sequencing and droplet assays, where the count matrix tends to be more sparse), a value of 0.1 is found to generally work well.

# Set output dir to scratch
outDir = ""

infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1, # Recommended for 10x Genomics data
                             out_dir=outDir, # set output dir
                             cluster_by_groups=TRUE, # clustering by cell types
                             denoise=TRUE,
                             HMM=TRUE,
                             num_threads=32) # Optimize compute time
print('InferCNV complete. Results folder can be found at /scratch.global/walk1195/orbit/hank/infercnv/')


### Results:

  # infercnv.preliminary.png : the preliminary inferCNV view (prior to denoising or HMM prediction)
  # infercnv.png : the final heatmap generated by inferCNV with denoising methods applied.
  # infercnv.references.txt : the 'normal' cell matrix data values.
  # infercnv.observations.txt : the tumor cell matrix data values
  # infercnv.observation_groupings.txt : group memberships for the tumor cells as clustered.
  # infercnv.observations_dendrogram.txt : the newick formatted dendrogram for the tumor cells that matches the heatmap.

### Run 2: Setting 'normal' cells as Myeloid AND T cells

print('Generating infercnv object .....')
infercnv_obj = CreateInfercnvObject(raw_counts_matrix=exp.rawdata, # Raw counts
                                    annotations_file=annotations, # Cell type annotations
                                    delim="\t",
                                    gene_order_file=paste0(gene_pos_path,"gene_positions.txt"), # Gene positions
                                    ref_group_names=c("T cells", "Myeloid cells"),
                                    chr_exclude = chrs_to_exclude) # Customized chr list excluding certain chrs


#### Run infercnv 
print('Running infercnv ......')

### On the cutoff parameter:
# The cutoff value determines which genes will be used for the infercnv analysis.
# Genes with a mean number of counts across cells will be excluded.
# For smart-seq (full-length transcript sequencing, typically using cell plate assays rather than droplets), a value of 1 works well.
# For 10x (and potentially other 3'-end sequencing and droplet assays, where the count matrix tends to be more sparse), a value of 0.1 is found to generally work well.

# Update output dir
outDir = paste0(outDir, 'run2')

# Read in infercnv object if needed
infercnv_obj <- 	readRDS(glue::glue(outDir,"run.final.infercnv_obj"))

infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1, # Recommended for 10x Genomics data
                             out_dir=outDir, # set output dir
                             cluster_by_groups=TRUE, # clustering by cell types
                             denoise=TRUE,
                             HMM=TRUE,
                             BayesMaxPNormal=0.3, # More stringent posterior threshold
                             num_threads=32, # Optimize compute time
                             leiden_resolution = 0.005) # Only for rerunning the subclustering
print('InferCNV complete.')


### Update plots as needed
plot_cnv(infercnv_obj,
         out_dir = outDir,
         title = 'InferCNV_test_plot',
         ref_title = 'Normal Cells',
         obs_title = 'Malignant Cells',
         cluster_by_groups = TRUE,
         color_safe_pal = TRUE,
         plot_chr_scale = FALSE,
         dynamic_resize =0.05,
         output_filename = "infercnv_test_plot")

#### Plots per group
plot_per_group(infercnv_obj,
               on_references = FALSE,
               on_observations = TRUE,
               sample = FALSE,
               out_dir = outDir)